# FEATURE - Admin Plugin
gruut/gruut pull request #106
Opened 2019-05-13 03:06 UTC by blackironj

- Admin Plugin 추가 
  - Admin Plugin은 Net plugin과 구조는 같습니다. 

- Admin command service를 위한 protobuf 작성
  - Protobuf에 대한 내용은 논의 되어야 합니다. 

- Admin Service rpc 추가

2019-05-13 04:03 UTC, blackironj commented on src/plugins/admin_plugin/rpc_services/proto/admin_service.proto
> +}
Protobuf  임시로 작성해 봤는데, 확인 부탁드릴게요. 고칠부분 혹 추가할 부분 있으면 말씀해주세요.
`req_json` `res_json` 은 json dump 한 형태입니다.

2019-05-13 04:34 UTC, morishjs requested changes

2019-05-13 04:34 UTC, park53kr commented on src/plugins/admin_plugin/admin_plugin.cpp
> +    builder.AddListeningPort("localhost:" + admin_port, grpc::InsecureServerCredentials());
대다수의 case에서 localhost의 노드를 접속하겠지만, 나중에 remote 노드 접속을 고려해서 ip address도 port처럼 설정으로 분리해주세요

2019-05-13 04:34 UTC, park53kr commented on src/plugins/admin_plugin/rpc_services/proto/admin_service.proto
> +}
@blackironj 
https://github.com/gruut/gruut-console/blob/master/protos/remote_control_service.proto

여기서 CheckStatus 도 같이 추가해주세요 (node가 현재 running 중인지 체크하기 위한 서비스)

2019-05-13 04:34 UTC, park53kr commented on src/plugins/admin_plugin/rpc_services/proto/admin_service.proto
> +}
@blackironj 

Request 의 구조를 
```c++
Command command;
string req_json;
```
위와 같이 하면 어떤 이점이 있을까요? 개인적인 의견은 현재 Network Message처럼 스키마를 코드로 정의해주는게 너무 불편한 것 같은데... protobuf에 메세지에 대한 spec을 적고, 스키마를 generate하는건 protobuf 컴파일러에게 위임하는게 낫지 않을까요?

2019-05-13 04:40 UTC, blackironj commented on src/plugins/admin_plugin/rpc_services/proto/admin_service.proto
> +}
@park53kr 
rpc를 여러개 만들자는 말씀이신거죠? 
그렇게 해도 괜찮을것 같습니다.

2019-05-13 04:40 UTC, park53kr commented on src/plugins/admin_plugin/rpc_services/proto/admin_service.proto
> +}
@blackironj 
네

2019-05-14 01:12 UTC, morishjs approved these changes

2019-05-14 01:24 UTC, merged