# ADD - Result query 관련 기능 추가
gruut/gruut pull request #181
Opened 2019-06-10 09:25 UTC by SeongKwangMoon

result query를 처리하는 부분 중 transfer와 같은 v.XX 부분의 구현을 우선으로 해둔 storage 코드입니다.
각 커밋들에 변경사항에 대한 설명이 있습니다.
한 번의 PR에 변경사항이 너무 많아졌는데, 앞으로는 좀 더 신경써서 쪼개서 PR해보도록 하겠습니다.

 ### 변경사항
state tree를 이루는 merkle tree가 mem_ledger로 통합되고, chain_plugin에 있던 요소들이 권한 관계에 따라 chain으로 옮기는 등의 작업들이 있었으며, 그 외에 unresolved block pool을 컨트롤하는 함수들이 더 자세히 구현되었습니다.

 ### TODO - Refactoring
중복되는 기능의 함수가 상당히 많습니다. 특히, State tree와 Contract tree를 따로 취급해야하는데 둘의 구성요소가 다르다보니 기능 자체는 거의 유사한데 함수를 따로 선언한 경우가 꽤 있습니다.
하나의 구조체 안에 여러 종류의 구조체를 다룰 수 있게 하고 함수 하나에서 데이터의 형태를 검사하는 방법도 고려해봤으나, 구조체에 대한 직관성이 떨어지고 결국 구조가 다른 부분은 if문 등으로 분기해야해서 비효율적이라고 판단하여 현재와 같이 구현해두었습니다.
더 좋은 방법이 있다면 말씀해주시면 반영하겠습니다.

그리고, block pool의 backup/restore는 주요 기능을 우선으로 해서 미루어두었는데, 구현 예정입니다.

pid에 따른 state tree의 구성과 구현이 정확히 되는지는 PR 이후 계속 검증할 예정입니다.

2019-06-10 09:26 UTC, SeongKwangMoon commented
현재 제 환경에서는 `error: no member named 'saveLatestWorldId' in 'tethys::KvController'` 같이 다른 부분의 코드에서 에러가 발생해서 빌드가 안 되고 있는데, 원인을 찾는 중입니다.

2019-06-10 09:40 UTC, blackironj commented
@SeongKwangMoon remote 환경에서 컴파일 하시면 
빌드에 필요한 파일 전체를 선택후 remote  환경에 다시 전송 후, cmake reset 후 다시 컴파일 해보세요.

2019-06-10 09:44 UTC, SeongKwangMoon commented
@blackironj 
Deployment로 동기화 하니까 빌드 잘 되네요

2019-06-11 01:31 UTC, blackironj approved these changes

2019-06-11 02:05 UTC, morishjs requested changes

2019-06-11 02:05 UTC, park53kr commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
table의 schema가 변경되면 schema.rb 에 변경사항이 반영되어야 하는데, schema.rb 변화가 없어요. 같이 반영해주세요

2019-06-11 02:51 UTC, SeongKwangMoon commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
@park53kr 
수정했습니다. 그런데 이 파일의 최상단에 `This file is auto-generated from the current state of the database.` 라고 쓰여있는데, 수동으로 수정해줘야하는게 맞는건가요?

2019-06-11 03:29 UTC, SeongKwangMoon commented
lib/tethys-utils 이 conflict라는데 최신 브랜치랑 merge해서 충돌 없는거 확인해도 저러네요.
해결법을 찾는 중입니다..

2019-06-11 04:58 UTC, park53kr commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
@SeongKwangMoon 
아뇨 schema.rb 는 건드리면 안됩니다.

2019-06-11 05:01 UTC, SeongKwangMoon commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
@park53kr 
그러면 구조를 변경할때마다 migrage를 매번 다시 해줘야하는건가요?
순차적으로 적용을 시도하다가 이미 있는 테이블이면 다음으로 넘어가는게 아니라 정지해버려서 테이블들을 전부 지워야 migrate가 제대로 작동하던데.. 그럼 매번 지웠다가 다시 migrate 해줘야하나요?

2019-06-11 05:07 UTC, park53kr commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
@SeongKwangMoon 
정상적인 workflow라면 `create_endorser` 같은 파일과 비슷한 새로운 스크립트 파일을 생성해야 합니다. 그 스크립트 파일에는 이미 존재하는 테이블의 컬럼을 수정하는 내용이 들어갈수도 있고 Index를 추가하는 내용들이 들어갈 수 있습니다. 하지만 지금은 개발단계라서 새로운 스크립트 파일을 만들어서 변경사항을 적용하는 것도 방법이지만 기존에 존재했던 migration 파일을 수정해서 반영하는 것도 하나의 방법이라서, 그 방법대로 하려면 데이터베이스 다 날리고(db:drop), 새로 생성하고(db:create) 마이그레이션을 반영(db:migrate) 해야죠.

2019-06-11 05:46 UTC, SeongKwangMoon commented on scripts/db/db/migrate/20190418061950_create_endorser.rb
> -      t.string :end_sig, limit: 100
@park53kr 
직접 수정 말고, 자동적으로 생성된 파일로 수정하였습니다.
remote server를 사용해서 테스트, 컴파일을 하다 보니 db 생성에 따른 자동생성 파일이 작업하는 PC에서는 반영이 안 되어서 일어나는 문제였습니다.
앞으로 db 구조가 바뀌면 체크해서 반영하겠습니다.

2019-06-11 05:48 UTC, SeongKwangMoon commented
그냥 콘솔로 merge할때는 문제가 안 생기네요. 해결하기 곤란하다 싶으면 그냥 콘솔로 merge 한 다음 이 PR은 수동으로 닫으면 될 것 같습니다.

2019-06-12 01:45 UTC, merged