Feature/add storage
gruut/gruut pull request #98
Opened 2019-05-03 07:38 UTC by SeongKwangMoon

Chain Plugin에 Strorage 관련 파일들을 merge합니다.

큰 변경점은 다음과 같습니다.
1. Storage 관련 파일들이 추가됩니다. 현재 구동은 블럭 정보를 담고 있는 json 파일을 파싱하여 처리가 되는것까지 확인하였으며, 저장까지는 아직 테스트하지 않았습니다. 이 커밋 이후 바로 테스트하여 추가할 예정입니다.

2. Key-Value Store를 담당하는 levelDB가 lib/ 에 추가됩니다.
변경된 파일을 확인하실 때, levelDB 관련 파일들은 전부 무시하셔도 됩니다.

그 외 변경사항 등은 각 커밋에 정리된 것이 있으니, 참조하시고 명확하지 않은 것이 있다면 추가로 질문해주세요.

2019-05-03 07:44 UTC, blackironj commented
`leveldb`  lib에 포함 하지말고, 설치해서 쓰는게 어떨까요? 혹시 GEN 할때 문제있었나요?

2019-05-03 07:46 UTC, SeongKwangMoon commented
저도 lib에 포함할지 고민하다가 여쭤보고 일단 포함시킨 거라서, 논의 후에 바꾸면 될 것 같습니다.
conflict는 지금 확인중입니다.

2019-05-07 00:11 UTC, blackironj commented on src/plugins/chain_plugin/config/config.hpp
> +        constexpr size_t MAX_SIGNER_NUM = 200;
되도록 size_t 안쓰는게 좋을거 같아요.

2019-05-07 00:11 UTC, blackironj commented on src/plugins/chain_plugin/config/storage_type.hpp
> +using block_height_type = size_t;
여기도 size_t 요

2019-05-07 01:04 UTC, park53kr commented
번거롭지 않다면 저는 설치해서 사용해도 상관없습니다.

2019-05-07 02:10 UTC, blackironj commented
@park53kr @SeongKwangMoon 
패키지 매니저에서 leveldb 1.20은 설치가 가능한거 같네요. 
cmake에서 find_package가 지원이 안돼서 따로 작성해야하는거 할 필요가 있을거같아요. 지금 어떻게 하는게 좋을까요?
`apt install libleveldb-dev`
`brew install leveldb`

2019-05-07 02:14 UTC, park53kr commented
그럼 find_package 관련 코드 작성하면 되지 않을까요?

2019-05-07 02:20 UTC, blackironj commented
https://github.com/BVLC/caffe/blob/master/cmake/Modules/FindLevelDB.cmake
이런거 고쳐쓰면 될 거 같습니다.

2019-05-07 02:42 UTC, SeongKwangMoon commented
그러면 일단 lib/ 쪽에서는 빼놓으면 될까요? 나중에 추가하기로 해도 그 때 다시 추가하면 될테니까요

2019-05-07 02:51 UTC, blackironj commented
@SeongKwangMoon 
현재 leveldb 관련 파일 lib에서 빼고, `FindLevelDb.cmake` 작성하고 leveldb는 설치해서 쓰는게 좋을거 같아요. 패키지 매니저로 설치할 수 있으니까.

2019-05-07 04:38 UTC, blackironj approved these changes
`FindLevedlDB.cmake` 는 수정이 필요해 보여요. 말씀하신대로 차후 leveldb 관련 작업하시면서 수정해주시면 될거 같습니다.

2019-05-07 07:52 UTC, morishjs requested changes
실제로 빌드해서 돌려보면 런타임에러가 발생합니다.

2019-05-07 07:52 UTC, park53kr commented on src/plugins/chain_plugin/CMakeLists.txt
> +        include/*.cpp
필요없는 코드입니다.
include/ 디렉토리에는 hpp만 들어가요

2019-05-07 07:52 UTC, park53kr commented on src/plugins/chain_plugin/include/static_merkle_tree.hpp
> +    auto min_addable_size = min(static_cast<uint64_t>(MAX_MERKLE_LEAVES), merkle_contents.size());
Merkle_content.size() 가 size_t 이므로, uint64_t로 형변환해야 합니다.

2019-05-07 08:11 UTC, SeongKwangMoon commented
@park53kr 
 런타임 에러가 발생하나요? 저는 지금 Chain만 활성화해서 실행 테스트해보고있는 중이긴 한데, Chain 플러그인만 활성화했을 때에는 런타임 에러가 발생하지 않는데 혹시 다른 부분과의 충돌이 있는걸까요?

2019-05-07 08:14 UTC, park53kr commented
@SeongKwangMoon 
아 그럼 다른 플러그인에서 에러가 발생하는 것 같습니다. 이 PR에서는 신경을 안 쓰셔도 될 것 같습니다.

2019-05-08 02:18 UTC, merged